=== FrancescaEN/gzoom-prova/gzoom-legacy/framework/webapp/dtd/site-conf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="site-conf">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="include"/>
                <xs:element minOccurs="0" ref="description"/>
                <xs:element minOccurs="0" ref="owner"/>
                <xs:element minOccurs="0" ref="errorpage"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="handler"/>
                <xs:element minOccurs="0" maxOccurs="1" ref="protect"/>
                <xs:element minOccurs="0" ref="firstvisit"/>
                <xs:element minOccurs="0" ref="preprocessor"/>
                <xs:element minOccurs="0" ref="postprocessor"/>
                <xs:element minOccurs="0" ref="after-login"/>
                <xs:element minOccurs="0" ref="before-logout"/>
                <xs:element minOccurs="0" maxOccurs="1" ref="default-request"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="request-map"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="view-map"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="include">
        <xs:annotation>
            <xs:documentation>
                This includes all elements of the controller.xml file references.

                Note that if you define any of the event blocks in this file (the including file) they
                will override (replace) the one in the included file, effectively emptying it. The event
                blocks are: firstvisit, preprocessor, postprocessor, after-login, and before-logout.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attributeGroup ref="attlist.include"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.include">
        <xs:attribute type="xs:string" name="location" use="required"/>
    </xs:attributeGroup>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="owner" type="xs:string"/>
    <xs:element name="errorpage" type="xs:string"/>
    <xs:element name="handler">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.handler"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.handler">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute name="type" default="request">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="view"/>
                    <xs:enumeration value="request"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="class" use="required"/>
    </xs:attributeGroup>
    <xs:element name="protect">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.protect"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.protect">
        <xs:attribute type="xs:string" name="view" use="required"/>
    </xs:attributeGroup>
    <xs:element name="firstvisit">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="event"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="preprocessor">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="event"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="postprocessor">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="event"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="after-login">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="event"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="before-logout">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="event"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="default-request">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.default-request"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.default-request">
        <xs:attribute type="xs:string" name="request-uri" use="required"/>
    </xs:attributeGroup>
    <xs:element name="request-map">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="description"/>
                <xs:element minOccurs="0" ref="security"/>
                <xs:element minOccurs="0" ref="event"/>
                <xs:element maxOccurs="unbounded" ref="response"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.request-map"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.request-map">
        <xs:attribute type="xs:string" name="uri" use="required"/>
        <xs:attribute name="edit" default="true">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="track-visit" default="true">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="track-serverhit" default="true">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:element name="security">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.security"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.security">
        <xs:attribute name="https" default="false">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="auth" default="false">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="cert" default="false">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="external-view" default="true">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="direct-request" default="true">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:element name="event">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.event"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.event">
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="path" type="xs:string"/>
        <xs:attribute name="invoke" type="xs:string"/>
        <xs:attribute name="global-transaction" default="true">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:element name="response">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="redirect-parameter"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.response"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.response">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="none"/>
                    <xs:enumeration value="view"/>
                    <xs:enumeration value="view-last">
                        <xs:annotation>
                            <xs:documentation>Will use the view from the last request unless there
                                is a saved from some previous request (using the save-last-view
                                attribute).  Use the value attribute to specify a default view
                                in case no previous view can be retrieved.</xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="view-last-noparam"/>                            
                    <xs:enumeration value="view-home">
                        <xs:annotation>
                            <xs:documentation>Will use the view from the last saved 'home' position
                                (using the save-home-view attribute).</xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="request"/>
                    <xs:enumeration value="request-redirect"/>
                    <xs:enumeration value="request-redirect-noparam"/>
                    <xs:enumeration value="request-last">
                        <xs:annotation>
                            <xs:documentation>Will use the request from the last request unless there
                                is a saved from some previous request (using the save-last-view
                                attribute).  Use the value attribute to specify a default view
                                in case no previous view can be retrieved.</xs:documentation>
                        </xs:annotation>
                    </xs:enumeration>
                    <xs:enumeration value="url"/>
                    <!-- Maps SPA -->
                    <xs:enumeration value="cross-redirect"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="save-last-view" default="false">
            <xs:annotation>
                <xs:documentation>Saves the last (previous) request's view for future use, generally
                    with the view-last type of response.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="save-current-view" default="false">
            <xs:annotation>
                <xs:documentation>Saves the current request's view for future use, generally with
                    the view-last type of response.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="save-home-view" default="false">
            <xs:annotation>
                <xs:documentation>Saves the current request's view for future use, generally with
                    the view-home type of response.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:element name="redirect-parameter">
        <xs:annotation><xs:documentation>Adds a parameter with the given name to the redirect. Finds value in a request attribute if exists, or a request parameter if no attribute is found.</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:attributeGroup ref="attlist.redirect-parameter"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.redirect-parameter">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="from" use="optional">
            <xs:annotation>
                <xs:documentation>If specified used instead of the value of name for the key to find
                    a request attribute or parameter.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:element name="view-map">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="description"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.view-map"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.view-map">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="page"/>
        <xs:attribute type="xs:string" name="type" default="default"/>
        <xs:attribute type="xs:string" name="info"/>
        <xs:attribute type="xs:string" name="content-type"/>
        <xs:attribute type="xs:string" name="encoding"/>
        <xs:attribute name="no-cache" default="false">
            <xs:annotation>
                <xs:documentation>Send no-cache headers if set to true.</xs:documentation>
            </xs:annotation>        
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>    
    </xs:attributeGroup>
</xs:schema>

=== FrancescaEN/gzoom-prova/gzoom-legacy/hot-deploy/base/webapp/common/WEB-INF/base-controller.xml
<?xml version="1.0" encoding="UTF-8"?>

<site-conf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://ofbiz.apache.org/dtds/site-conf.xsd">
    <!-- The controller elements that are common to all OFBiz components
        can be found in the following xml file. A component can override the
        elements found in the common-controller.xml file. -->
    <include location="component://common/webcommon/WEB-INF/common-controller.xml"/>

    <description>Base Component Site Configuration File</description>
    <owner></owner>

    <handler name="birt-content" type="view" class="com.mapsengineering.base.birt.webapp.view.BirtViewHandler"/>
    <handler name="xmlrpc" type="request" class="com.mapsengineering.base.events.XmlRpcEventHandler"/>
    
    <!-- Events to run on every request before security (chains exempt) -->
    <preprocessor>
        <!-- Events to run on every request before security (chains exempt) -->
        <event name="checkSaveView" type="java" path="com.mapsengineering.base.events.SessionHistoryWorker" invoke="checkSaveView"/>
        <event name="putCookiesInContext" type="java" path="com.mapsengineering.base.events.CookieEvents" invoke="putCookiesInContext"/>
        <event name="readFindQueryString" type="java" path="com.mapsengineering.base.events.SessionHistoryWorker" invoke="readFindQueryString"/>
    </preprocessor>
    <!-- Events to run on every request after all other processing (chains exempt) -->

    <postprocessor>
        <event name="storeFindQueryString" type="java" path="com.mapsengineering.base.events.SessionHistoryWorker" invoke="storeFindQueryString"/>
        <event name="readReturnBackAreaId" type="java" path="com.mapsengineering.base.events.SessionHistoryWorker" invoke="readReturnBackAreaId"/>
        <!-- TODO vedere se Ã¨ il posto giusto -->
        <event name="getLanguageSettings" type="java" path="com.mapsengineering.base.events.LanguageLocaleEvent" invoke="getLanguageSettings"/>
     </postprocessor>

    <after-login>
        <event name="addExternalLoginKeyToCookie" type="java" path="com.mapsengineering.base.events.CookieEvents" invoke="addExternalLoginKeyToCookie"/>
    </after-login>


    <!-- Request Mappings -->
    <request-map uri="main">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="main"/>
    </request-map>
    <request-map uri="authview">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="main"/>
    </request-map>
    <request-map uri="setSessionLocale">
        <security https="true" auth="false"/>
        <event type="java" path="org.ofbiz.common.CommonEvents" invoke="setSessionLocale"/>
        <response name="success" type="view" value="main"/>
        <response name="error" type="request" value="main"/>
    </request-map>
    <request-map uri="setSessionOrganizzationId">
        <security https="true" auth="true"/>
        <event type="java" path="org.ofbiz.common.CommonEvents" invoke="setSessionOrganizzationId"/>
        <response name="success" type="request" value="main"/>
        <response name="error" type="request" value="main"/>
    </request-map>
    
    <request-map uri="getMessage">
        <event type="service" invoke="getMessage"/>
        <response name="success" type="request" value="json"/>
        <response name="error" type="request" value="json"/>
    </request-map>

    <request-map uri="search">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="search"/>
        <response name="error" type="view" value="error"/>
    </request-map>
    <request-map uri="searchContainerOnly">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="searchContainerOnly"/>
        <response name="error" type="view" value="error"/>
    </request-map>

    <request-map uri="startSearch">
        <security https="true" auth="true"/>
        <event type="groovy" path="com/mapsengineering/base/" invoke="executePerformFind.groovy"/>
        <response name="success" type="view" value="search"/>
        <response name="management" type="view" value="management"/>
        <response name="error" type="view" value="search"/>
    </request-map>
    <request-map uri="searchResultContainerOnly">
        <security https="true" auth="true"/>
        <event type="groovy" path="com/mapsengineering/base/" invoke="executePerformFind.groovy"/>
        <response name="success" type="view" value="searchResultContainerOnly"/>
        <response name="export-search" type="view" value="searchResultContainerOnlyExport"/>
        <response name="management" type="view" value="managementContainerOnly"/>
    </request-map>

    <!-- Common lookup request -->
    <request-map uri="lookup">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="lookup"/>
        <response name="error" type="view" value="error"/>
    </request-map>

    <!-- Client validation -->
    <request-map uri="fieldValidation">
        <security https="true" auth="true"/>
        <event type="service" invoke="fieldValidation"/>
        <response name="success" type="view" value="fieldValidation"/>
        <response name="error" type="view" value="fieldValidation"/>
    </request-map>


    <request-map uri="management">
        <security https="true" auth="true"/>
        <event type="groovy" path="com/mapsengineering/base/" invoke="populateManagement.groovy"/>
        <response name="success" type="view" value="management"/>
        <response name="wizard" type="view" value="wizard"/>
    </request-map>
    <request-map uri="managementContainerOnly">
        <security https="true" auth="true"/>
        <event type="groovy" path="com/mapsengineering/base/" invoke="populateManagement.groovy"/>
        <response name="success" type="view" value="managementContainerOnly"/>
        <response name="search" type="view" value="searchResultContainerOnly"/>
        <response name="searchRequest" type="request" value="readFindQueryString"/>
        <response name="wizard" type="view" value="wizardOnly"/>
    </request-map>
    <request-map uri="readFindQueryString">
        <security https="true" auth="true"/>
        <event name="readFindQueryString" type="java" path="com.mapsengineering.base.events.SessionHistoryWorker" invoke="readFindQueryString"/>
        <response name="success" type="request" value="searchResultContainerOnly"/>
    </request-map>
    <request-map uri="subFolderManagementContainerOnly">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="subFolderManagementContainerOnly"/>
    </request-map>
    <request-map uri="childManagementContainerOnly">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="childManagementContainerOnly"/>
    </request-map>
    <request-map uri="childManagementListContainerOnly">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="childManagementListContainerOnly"/>
    </request-map>

    <request-map uri="showPortalPageContainerOnly">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="showPortalPageContainerOnly"/>
    </request-map>
    <request-map uri="showPortletContainerOnly">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="showPortletContainerOnly"/>
    </request-map>
    <request-map uri="showPortalPageMainContainerOnly">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="showPortalPageMainContainerOnly"/>
    </request-map>
    <request-map uri="showPortalPageMainMenuContainerOnly">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="showPortalPageMainMenuContainerOnly"/>
    </request-map>

	<request-map uri="box">
        <security https="true" auth="true"/>
        <event type="groovy" path="com/mapsengineering/base/" invoke="dispatcherRequest.groovy"/>
        <response name="success" type="none"/>
        <response name="error" type="view" value="error"/>
    </request-map>
    
    <!-- Wizard -->
    <request-map uri="wizard">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="wizard"/>
    </request-map>
    <request-map uri="wizardOnly">
        <security https="true" auth="true"/>
        <response name="success" type="view" value="wizardOnly"/>
    </request-map>

    <request-map uri="wizardNext">
        <security https="true" auth="true"/>
        <event type="java" path="com.mapsengineering.base.events.WizardEvents" invoke="storeWizardData"/>
        <response name="success" type="request" value="wizard"/>
        <response name="error" type="view" value="wizard"/>
    </request-map>
    <request-map uri="wizardNextOnly">
        <security https="true" auth="true"/>
        <event type="java" path="com.mapsengineering.base.events.WizardEvents" invoke="storeWizardData"/>
        <response name="success" type="view" value="wizardOnly"/>
        <response name="error" type="view" value="wizardOnly"/>
    </request-map>

    <request-map uri="wizardPrevious">
        <security https="true" auth="true"/>
        <event type="java" path="com.mapsengineering.base.events.WizardEvents" invoke="popWizardData"/>
        <response name="success" type="request" value="wizard"/>
        <response name="error" type="view" value="wizard"/>
    </request-map>
    <request-map uri="wizardPreviousOnly">
        <security https="true" auth="true"/>
        <event type="java" path="com.mapsengineering.base.events.WizardEvents" invoke="popWizardData"/>
